.TH "Interesting" 2 "2023年 十一月 29日 星期三" "Version 0.1" "number magician roman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Interesting \- number guessing gamer (A recursive?) 
This is free and unencumbered software released into the public domain\&.
.PP
(maybe)
.PP
What can I say? Very simple program\&.
.PP
Use devide-in-two method\&. From 1 to 100\&.
.PP
New function: number in roman style
.SH "AUTHORS"
.PP
This program is belong to
.IP "\(bu" 2
\fCMeng Lingqian\fP 
.PP

