.TH "numMagician" 2 "2023年 十一月 29日 星期三" "Version 0.1" "number magician roman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
numMagician \- Interesting number guessing gamer
.SH "SYNOPSIS"
.PP
\fCnumMagician\fP [ \fIpattern\fP ] 
.SH "DESCRIPTION"
.PP
Play a number guessing game (number style related to \fIpattern\fP)\&.
